// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPjdk9DxP9j23UwcgUnsE95kfFvhX7D4',
    appId: '1:706851265772:web:90ad5ffdc690e08e4519c9',
    messagingSenderId: '706851265772',
    projectId: 'flutter-app1-15b84',
    authDomain: 'flutter-app1-15b84.firebaseapp.com',
    storageBucket: 'flutter-app1-15b84.appspot.com',
    measurementId: 'G-804LV2V2VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6jeufbnn5A-p65LlmWy8L4LXx8ID2qA',
    appId: '1:706851265772:android:01316c12eb1484294519c9',
    messagingSenderId: '706851265772',
    projectId: 'flutter-app1-15b84',
    storageBucket: 'flutter-app1-15b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilNVtuBfn4HmuqP5MvYzy-vAWoT5GeEQ',
    appId: '1:706851265772:ios:61a44c12fd94fa2c4519c9',
    messagingSenderId: '706851265772',
    projectId: 'flutter-app1-15b84',
    storageBucket: 'flutter-app1-15b84.appspot.com',
    iosBundleId: 'com.example.app1Octavio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDilNVtuBfn4HmuqP5MvYzy-vAWoT5GeEQ',
    appId: '1:706851265772:ios:ba9e06e42b675ef24519c9',
    messagingSenderId: '706851265772',
    projectId: 'flutter-app1-15b84',
    storageBucket: 'flutter-app1-15b84.appspot.com',
    iosBundleId: 'com.example.app1Octavio.RunnerTests',
  );
}
